/*
 * Author: Nikolay Dvurechensky
 * Site: https://dvurechensky.pro/
 * Gmail: dvurechenskysoft@gmail.com
 * Last Updated: 23 апреля 2026 06:53:22
 * Version: 1.0.19
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Root {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setAccountDir {
            get {
                return ((string)(this["setAccountDir"]));
            }
            set {
                this["setAccountDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setIonCrossDir {
            get {
                return ((string)(this["setIonCrossDir"]));
            }
            set {
                this["setIonCrossDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWriteEncryptedFiles {
            get {
                return ((bool)(this["setWriteEncryptedFiles"]));
            }
            set {
                this["setWriteEncryptedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string setFLHookIP {
            get {
                return ((string)(this["setFLHookIP"]));
            }
            set {
                this["setFLHookIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1919")]
        public decimal setFLHookPort {
            get {
                return ((decimal)(this["setFLHookPort"]));
            }
            set {
                this["setFLHookPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string setFLHookPassword {
            get {
                return ((string)(this["setFLHookPassword"]));
            }
            set {
                this["setFLHookPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setFLDir {
            get {
                return ((string)(this["setFLDir"]));
            }
            set {
                this["setFLDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCheckChangedOnly {
            get {
                return ((bool)(this["setCheckChangedOnly"]));
            }
            set {
                this["setCheckChangedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setFLHookUnicode {
            get {
                return ((bool)(this["setFLHookUnicode"]));
            }
            set {
                this["setFLHookUnicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal setDaysToDeleteInactiveChars {
            get {
                return ((decimal)(this["setDaysToDeleteInactiveChars"]));
            }
            set {
                this["setDaysToDeleteInactiveChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public decimal setSecsToDeleteUninterestedChars {
            get {
                return ((decimal)(this["setSecsToDeleteUninterestedChars"]));
            }
            set {
                this["setSecsToDeleteUninterestedChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setAutomaticCharWipe {
            get {
                return ((bool)(this["setAutomaticCharWipe"]));
            }
            set {
                this["setAutomaticCharWipe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setAutomaticCharClean {
            get {
                return ((bool)(this["setAutomaticCharClean"]));
            }
            set {
                this["setAutomaticCharClean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\web\\stats")]
        public string setStatisticsDir {
            get {
                return ((string)(this["setStatisticsDir"]));
            }
            set {
                this["setStatisticsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setStatsFactions {
            get {
                return ((string)(this["setStatsFactions"]));
            }
            set {
                this["setStatsFactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCheckDefaultEngine {
            get {
                return ((bool)(this["setCheckDefaultEngine"]));
            }
            set {
                this["setCheckDefaultEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCheckDefaultPowerPlant {
            get {
                return ((bool)(this["setCheckDefaultPowerPlant"]));
            }
            set {
                this["setCheckDefaultPowerPlant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setReportVisitErrors {
            get {
                return ((bool)(this["setReportVisitErrors"]));
            }
            set {
                this["setReportVisitErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setAutomaticFixErrors {
            get {
                return ((bool)(this["setAutomaticFixErrors"]));
            }
            set {
                this["setAutomaticFixErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setDebug {
            get {
                return ((decimal)(this["setDebug"]));
            }
            set {
                this["setDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setCheckDefaultLights {
            get {
                return ((bool)(this["setCheckDefaultLights"]));
            }
            set {
                this["setCheckDefaultLights"] = value;
            }
        }
    }
}
